# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ece1b677107d9c9d8bbfafa0e8caf80a9dbaf4f2dd9e86b1b07b97632ce8a13696ea5f6cb78a8ac7c7fd446f851fc3a061150ec53114ded62dc4e405ad2165

test:
  secret_key_base: e75ac42dc38696488c063b4067c47ef6ce2129e5f3b7a03f559e1ebd4b64d34b6c64312efda1f14e124196ebc3a6aee05a7acb844d8fbe28cc1a6954d38ac4f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
